version: "3.7"
services:
  app:
    image: docker.io/bitnami/laravel:8
    ports:
      - 80:8000    
    container_name: expertel-app        
    environment:
      - DB_HOST=mysql
    volumes:
      - ./:/app
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: expertel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/.expertel/data/mysql:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge